

### 0. User Sign up
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "username": "badirusubomi",
  "password": "password"
}

### 1. User login
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "username": "badirumoni",
  "password": "password"
}


### 1b. Get logged in user info
GET http://localhost:8080/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZGlydW1vbmkiLCJpYXQiOjE3NDg0MjU2MjYsImV4cCI6MTc0ODQyOTIyNn0.7WS-jxj27ggHZZT9-YBdrJxXmQKXxV3cDoBZjJJYyC8




### 2. Get cart items
GET http://localhost:8080/cart/6835e0e56c6836d2aae3bbc1e6133bc11a9af22c368af072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZGlydW1vbmkiLCJpYXQiOjE3NDg0MjU2MjYsImV4cCI6MTc0ODQyOTIyNn0.7WS-jxj27ggHZZT9-YBdrJxXmQKXxV3cDoBZjJJYyC8

### 3. Add a grocery Item
POST http://localhost:8080/cart/6835e0e56c9af22c368af072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZGlydW1vbmkiLCJpYXQiOjE3NDg0MTY0MDIsImV4cCI6MTc0ODQyMDAwMn0.ulrcxtBql49d-Xxnz6yyAkORD3HBNxMw44XlgHUFv2I

{
  "name": "Milk",
  "description": "Non Dairy",
  "quantity": 300
}

### 4. Update Grocery 
PATCH http://localhost:8080/cart/6835e0e56c9af22c368af072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZGlydW1vbmkiLCJpYXQiOjE3NDg0MjE5NzQsImV4cCI6MTc0ODQyNTU3NH0.CfVDgVk3ZtrNOt7f6msjZ1OwGfbHHr31jXK88Furf5U

{
  "groceryItemId": "6836c1aace1b4239e811e667",
  "name": "Milk",
  "quantity": 99,
  "description": "Non dairy - Modified description 2"
}

### 2. Delete Grocery 
DELETE  http://localhost:8080/cart/6835e0e56c9af22c368af072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhZGlydW1vbmkiLCJpYXQiOjE3NDg0MTY0MDIsImV4cCI6MTc0ODQyMDAwMn0.ulrcxtBql49d-Xxnz6yyAkORD3HBNxMw44XlgHUFv2I

{
  "groceryItemId":"6835e33d20c732e102a4259f",
  "reason": "test for deletion"
}